### ISSUE TITLE
Google Docs API gets removed

### ISSUE THREAD

**Issue by mutantcornholio** [dougmoscrop/serverless-plugin-common-excludes#15]
I had to add this:
```yml
package:
  include:
      - node_modules/googleapis/build/src/apis/docs/index.js
      - node_modules/googleapis/build/src/apis/docs/v1.js
```

because `serverless-plugin-common-excludes` deletes all the `docs/***`, including... Google Docs
